name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: docker.io/cypress/browsers

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: mobile-dev-inc/action-maestro-cloud@v2.0.2
        with:
          api-key: rb_SQkQCyUZEWHBNiy46E3TYzxZxqfqsCcQYXJqxwgJkTLU7m5JwkZMztvWRPNEytZl1vIpBqu8rsJrz4CGMxUQUCqOlzDBGanHeeK
          project-id: proj_01kjbftdsye4f9dqavy9nhs0fz
          app-file: qazandofood.apk