name: Build and run Maestro tests (Native Android)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  maestro-cloud:
    runs-on: ubuntu-latest

    container:
      image: docker.io/cypress/browsers

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: mobile-dev-inc/action-maestro-cloud@v2.0.2
        with:
          api-key: rb_qrou5mJ5xbXwmPlGuRlZmOS8lQMu0K3FFuC4zX3PKOv9EIfHHW7slVpnWzqzmeM4DdTQqQSaffu1XQIz5h8Mbu3Sl5oP4tkQEKj
          project-id: proj_01kjbftdsye4f9dqavy9nhs0fz
          app-file: qazandofood