name: Build and run Maestro tests (Native Android)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17        # ⚠️ prefira 17, o 11 está obsoleto em muitos projetos
          distribution: 'temurin'

      - name: Build APK
        run: ./gradlew assembleDebug

     
      - uses: mobile-dev-inc/action-maestro-cloud@v2.0.2
        with:
          api-key: rb_AYhWA9eHGSIo6sjqCiF06OWINTauVmsuoh7wRmwKla4HaJcKp2gyI0O79yHHtAzTDjbRwWWxCo7HEBizY2Az0RAH3CSCYBQ4Kxj  # ⚠️ veja aviso abaixo
          project-id: proj_01kjbftdsye4f9dqavy9nhs0fz
          app-file: qazandofood.apk